/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/sync-fonts.ts — DO NOT EDIT BY HAND.
 * Regenerate with: npm run prebuild   (runs automatically before dev/build)
 *
 * Display : Instrument Serif
 * Body    : Satoshi
 * Data    : JetBrains Mono (variable)
 *
 * Satoshi static — resolved 3 weight(s) from src/fonts/custom/.
 */
import localFont from 'next/font/local';

/** Display — headlines, section headings, hero. Single weight by design. */
export const displayFont = localFont({
  src: [
    { path: '../fonts/vendor/instrument-serif-latin-400-normal.woff2', weight: '400', style: 'normal' },
    { path: '../fonts/vendor/instrument-serif-latin-ext-400-normal.woff2', weight: '400', style: 'normal' },
  ],
  variable: '--fontstack-display',
  display: 'swap',
  preload: true,
  fallback: ['Fraunces', 'Iowan Old Style', 'Georgia', 'serif'],
  adjustFontFallback: false,
});

/** Body / UI — everything that is not a headline or a spec value. */
export const bodyFont = localFont({
  src: [
    { path: '../fonts/custom/Satoshi-Regular.woff2', weight: '400', style: 'normal' },
    { path: '../fonts/custom/Satoshi-Medium.woff2', weight: '500', style: 'normal' },
    { path: '../fonts/custom/Satoshi-Bold.woff2', weight: '600', style: 'normal' },
  ],
  variable: '--fontstack-body',
  display: 'swap',
  preload: true,
  fallback: ['Inter', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'],
  adjustFontFallback: false,
});

/** Data — HS codes, MOQs, lead times, Incoterms, port codes, cert numbers. */
export const dataFont = localFont({
  src: [
    { path: '../fonts/vendor/jetbrains-mono-latin-wght-normal.woff2', weight: '100 900', style: 'normal' },
    { path: '../fonts/vendor/jetbrains-mono-latin-ext-wght-normal.woff2', weight: '100 900', style: 'normal' },
  ],
  variable: '--fontstack-data',
  display: 'swap',
  preload: true,
  fallback: ['JetBrains Mono', 'Geist Mono', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
  adjustFontFallback: false,
});

/** True when the real brand body face is in place. Surfaced on /styleguide. */
export const BODY_FONT_FAMILY = "Satoshi";
export const BODY_FONT_IS_FALLBACK = false;

export const fontVariables = [
  displayFont.variable,
  bodyFont.variable,
  dataFont.variable,
  displayFont.className,
  bodyFont.className,
  dataFont.className,
].join(' ');
