/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/sync-fonts.ts — DO NOT EDIT BY HAND.
 * Regenerate with: npm run prebuild   (runs automatically before dev/build)
 *
 * Display : Instrument Serif
 * Body    : Inter  (FALLBACK — Satoshi not yet uploaded)
 * Data    : Geist Mono (variable)
 *
 * FALLBACK — Satoshi not found in src/fonts/custom/. Inter is the fallback named in the
 * brand document. Drop Satoshi-*.woff2 into src/fonts/custom/ and rebuild to swap.
 */
import localFont from 'next/font/local';

/** Display — headlines, section headings, hero. Single weight by design. */
export const displayFont = localFont({
  src: [
    { path: '../fonts/vendor/instrument-serif-latin-400-normal.woff2', weight: '400', style: 'normal' },
    { path: '../fonts/vendor/instrument-serif-latin-ext-400-normal.woff2', weight: '400', style: 'normal' },
  ],
  variable: '--fontstack-display',
  display: 'swap',
  preload: true,
  fallback: ['Fraunces', 'Iowan Old Style', 'Georgia', 'serif'],
  adjustFontFallback: false,
});

/** Body / UI — everything that is not a headline or a spec value. */
export const bodyFont = localFont({
  src: [
    { path: '../fonts/vendor/inter-latin-400-normal.woff2', weight: '400', style: 'normal' },
    { path: '../fonts/vendor/inter-latin-500-normal.woff2', weight: '500', style: 'normal' },
    { path: '../fonts/vendor/inter-latin-600-normal.woff2', weight: '600', style: 'normal' },
  ],
  variable: '--fontstack-body',
  display: 'swap',
  preload: true,
  fallback: ['Inter', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'],
  adjustFontFallback: false,
});

/** Data — HS codes, MOQs, lead times, Incoterms, port codes, cert numbers. */
export const dataFont = localFont({
  src: [
    { path: '../fonts/vendor/geist-mono-latin-wght-normal.woff2', weight: '100 900', style: 'normal' },
    { path: '../fonts/vendor/geist-mono-latin-ext-wght-normal.woff2', weight: '100 900', style: 'normal' },
  ],
  variable: '--fontstack-data',
  display: 'swap',
  preload: true,
  fallback: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
  adjustFontFallback: false,
});

/** True when the real brand body face is in place. Surfaced on /styleguide. */
export const BODY_FONT_FAMILY = "Inter";
export const BODY_FONT_IS_FALLBACK = true;

export const fontVariables = `${displayFont.className} ${bodyFont.className} ${dataFont.className}`;
